#!/usr/bin/env bash
# install nginx on rmserver
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 644 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart 
