#!/usr/bin/env bash
# configure Nginx server
sudo apt-get install nginx -y
sudo service nginx start
str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "22i $str" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
