#!/usr/bin/env bash
# This folowing script writes "Best School"x 10
i=1
while [[ $i -le 10 ]]; do
  if [[ $i == 8 ]]; then
    echo "good luck"
  elif [[ $i == 4 ]]; then
    echo "bad luck"
  else
    echo "Best School"
  fi
  i=$((i+1))
done
