#!/usr/bin/env bash
# This script provide you with information related to school file
f="school"
if [[ -e $f ]]; then
  echo "school file exists"
  if [[ ! (-s $f) ]]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi
  if [ -f $f ]; then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
