#!usr/bin/env bash
# This sript deny incoming traffic except ssh,hhtp,https

sudo apt update
sudo apt install -y ufw
sudeo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
